matrix:
  include:
    - os: osx
      language: generic

script:
  - ./build_mac.sh

deploy:
  provider: releases
  api_key: GITHUB_OAUTH_TOKEN
  file_glob: true
  file: ./SDL2_gfx*.dmg
  skip_cleanup: true
  on:
    tags: true
 