image:
  - Visual Studio 2015
#  - macos-mojave

install:
  - cmd: vcpkg install sdl2-gfx:x86-windows
  - cmd: vcpkg install sdl2-gfx:x64-windows

build: false

build_script:
#  - sh: ./build_mac.sh
  - cmd: python build_win.py

artifacts:
  - path: 'SDL2_gfx*.zip'
#  - path: SDL2_gfx*.dmg

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  artifact: /.*\.zip/
  provider: GitHub
  force_update: true
  auth_token:
    secure: yaWATFG8fFQjcXnP9D/CyVkZ5DsAs7kpS7MViOpBK7IuepzyWB2AHNo2dn5d/16b
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
